name: taskflow_application
description: "Flow IC Attendance System"
publish_to: 'none'
version: 0.1.4

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  lottie: ^3.1.2
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  http: ^1.2.2
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  intl: ^0.19.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  syncfusion_flutter_gauges: ^26.1.41
  syncfusion_flutter_datepicker: ^26.1.42
  shimmer: ^3.0.0
  flutter_custom_month_picker: ^0.1.3
  month_picker_dialog: ^5.0.0
  loading_animation_widget: ^1.2.1
  file_picker: ^8.1.2
  path: ^1.9.0
  device_info_plus: ^10.1.2
  image_picker: ^1.1.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Beta.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
    - assets/icons/